repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.3.5"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@2.1.2"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
  - repo: https://github.com/adehad/pre-commit-hooks
    rev: b581e6c14a9fbd9c6d37452761b525be6737b97b
    hooks:
      - id: arabic-presentation-form
        entry: arabic-presentation-form
        language: python
        types_or: [text, json, ts, markdown]
        args: [--excluded-chars, (ﷺ|﴿|﴾)]
        files: ^src/content/
        exclude: |
            (?x)^(
                src/content/shared/quran.ts|
                src/content/mawlids-shimmering-light.ts|
            )$
  - repo: local
    hooks:
    -   id: normalize-arabic-chars
        name: Normalize Arabic Characters
        entry: bun run scripts/normalize-arabic.ts
        language: node
        types: [ts]
        files: ^src/content/
        exclude: |
            (?x)^(
                src/content/shared/quran.ts|
                src/content/mawlids-shimmering-light.ts|
            )$
